Repository prisma-korea/prisma-nexus-apollo-boilerplate, pull requests merged in 2020-05, with the labels that each got.

#2 Refactor 'src/types' folder structure
  src/server.ts
  src/types/index.ts
  src/types/models/AuthPayload.ts
  src/types/models/Post.ts
  src/types/models/Scalar.ts
  src/types/models/User.ts
  src/types/models/index.ts
  src/types/resolvers/Mutation.ts
  src/types/resolvers/Query.ts
  src/types/resolvers/index.ts
  src/utils.ts
Labels: refactor

#3 Add subscription examples
  schema.graphql
  src/types/resolvers/Mutation.ts
  src/types/resolvers/Subscription.ts
  src/types/resolvers/index.ts
Labels: feature

#4 Enhance test coverage
  jest.config.js
  schema.graphql
  src/server.ts
  src/types/resolvers/Mutation.ts
  tests/queries.ts
  tests/resolvers.test.ts
  tests/testSetup.ts
  tests/user.test.ts
Labels: enhancement

#8 Upgrade packages
  .eslintrc.js
  jest.config.js
  package.json
  tests/setup/testSetup.ts
  yarn.lock
Labels: upgrade packages
